export interface Event {
    eventId: number;
    eventCompanyId: number;
    eventName: string;
    eventType: string;
    place: string;
    placeId: string;
    eventImage: string;
    eventInq: string;
    eventDesc: string;
    eventStatus: string;
    startDate: string;
    endDate: string;
    regDate: string;
    lastUpdatedDate: string;
    deletedDate: string;
    link: string;
}

export interface RegistEvent {
    eventCompanyId: number;
    eventName: string;
    eventType: string;
    place: string;
    placeId: string;
    eventImage: string | undefined;
    eventInq: string;
    eventDesc: string;
    startDate: string;
    endDate: string;
    link:"";
}

export interface EventList {
    eventId: number;
    eventName: string;
    startDate: string;
    eventStatus: string;
}

export interface EndedEvent extends Event {
    client: number;
    part: number;
    totalFee: number;
}

export const INIT_EVENT: Event = {
    eventId: -1,
    eventName: "",
    eventType: "",
    place: "",
    eventImage: "",
    eventInq: "",
    eventDesc: "",
    eventStatus: "",
    startDate: "",
    endDate: "",
    regDate: "",
    eventCompanyId: 0,
    lastUpdatedDate: "",
    deletedDate: "",
    link: "",
    placeId: ""
}

export const DUMMY_EVENT1: Event = {
    eventId: 2,
    eventName: "KB Killing Boys Concert",
    eventType: "concert",
    place: "잠실 올림픽 경기장",
    eventImage: "event1.jpg",
    eventInq: "02-123-456",
    eventDesc: "대세 남자 아이돌 콘서트",
    eventStatus: "Y",
    startDate: "2023.05.17",
    endDate: "2023.05.17",
    regDate: "2023.05.17",
    eventCompanyId: 0,
    lastUpdatedDate: "",
    deletedDate: "",
    link: "",
    placeId: ""
}

export const DUMMY_EVENT2: Event = {
    eventId: 3,
    eventName: "호구와트 마술쇼",
    eventType: "concert",
    place: "잠실 올림픽 경기장",
    eventImage: "event2.jpg",
    eventInq: "02-123-456",
    eventDesc: "마술쇼",
    eventStatus: "N",
    startDate: "2023.05.14",
    endDate: "2023.05.14",
    regDate: "2023.05.14",
    eventCompanyId: 0,
    lastUpdatedDate: "",
    deletedDate: "",
    link: "",
    placeId: ""
}

export const RegionList = [
    { id:"11", content:"서울특별시" },
    { id:"26", content:"부산광역시" },
    { id:"27", content:"대구광역시" },
    { id:"28", content:"인천광역시" },
    { id:"29", content:"광주광역시" },
    { id:"30", content:"대전광역시" },
    { id:"31", content:"울산광역시" },
    { id:"36", content:"세종특별자치시" },
    { id:"41", content:"경기도" },
    { id:"42", content:"강원도" },
    { id:"43", content:"충청북도" },
    { id:"44", content:"충청남도" },
    { id:"45", content:"전라북도" },
    { id:"46", content:"전라남도" },
    { id:"47", content:"경상북도" },
    { id:"48", content:"경상남도" },
    { id:"50", content:"제주특별자치도" },
];

export const RegionDetailList = [
    { id:"1111", content:"서울특별시종로구" },
    { id:"1114", content:"서울특별시중구" },
    { id:"1117", content:"서울특별시용산구" },
    { id:"1120", content:"서울특별시성동구" },
    { id:"1121", content:"서울특별시광진구" },
    { id:"1123", content:"서울특별시동대문구" },
    { id:"1126", content:"서울특별시중랑구" },
    { id:"1129", content:"서울특별시성북구" },
    { id:"1130", content:"서울특별시강북구" },
    { id:"1132", content:"서울특별시도봉구" },
    { id:"1135", content:"서울특별시노원구" },
    { id:"1138", content:"서울특별시은평구" },
    { id:"1141", content:"서울특별시서대문구" },
    { id:"1144", content:"서울특별시마포구" },
    { id:"1147", content:"서울특별시양천구" },
    { id:"1150", content:"서울특별시강서구" },
    { id:"1153", content:"서울특별시구로구" },
    { id:"1154", content:"서울특별시금천구" },
    { id:"1156", content:"서울특별시영등포구" },
    { id:"1159", content:"서울특별시동작구" },
    { id:"1162", content:"서울특별시관악구" },
    { id:"1165", content:"서울특별시서초구" },
    { id:"1168", content:"서울특별시강남구" },
    { id:"1171", content:"서울특별시송파구" },
    { id:"1174", content:"서울특별시강동구" },
    { id:"2600", content:"부산광역시" },
    { id:"2611", content:"부산광역시중구" },
    { id:"2614", content:"부산광역시서구" },
    { id:"2617", content:"부산광역시동구" },
    { id:"2620", content:"부산광역시영도구" },
    { id:"2623", content:"부산광역시부산진구" },
    { id:"2626", content:"부산광역시동래구" },
    { id:"2629", content:"부산광역시남구" },
    { id:"2632", content:"부산광역시북구" },
    { id:"2635", content:"부산광역시해운대구" },
    { id:"2638", content:"부산광역시사하구" },
    { id:"2641", content:"부산광역시금정구" },
    { id:"2644", content:"부산광역시강서구" },
    { id:"2647", content:"부산광역시연제구" },
    { id:"2650", content:"부산광역시수영구" },
    { id:"2653", content:"부산광역시사상구" },
    { id:"2671", content:"부산광역시기장군" },
    { id:"2700", content:"대구광역시" },
    { id:"2711", content:"대구광역시중구" },
    { id:"2714", content:"대구광역시동구" },
    { id:"2717", content:"대구광역시서구" },
    { id:"2720", content:"대구광역시남구" },
    { id:"2723", content:"대구광역시북구" },
    { id:"2726", content:"대구광역시수성구" },
    { id:"2729", content:"대구광역시달서구" },
    { id:"2771", content:"대구광역시달성군" },
    { id:"2800", content:"인천광역시" },
    { id:"2811", content:"인천광역시중구" },
    { id:"2814", content:"인천광역시동구" },
    { id:"2817", content:"인천광역시남구" },
    { id:"2818", content:"인천광역시연수구" },
    { id:"2820", content:"인천광역시남동구" },
    { id:"2823", content:"인천광역시부평구" },
    { id:"2824", content:"인천광역시계양구" },
    { id:"2826", content:"인천광역시서구" },
    { id:"2871", content:"인천광역시강화군" },
    { id:"2872", content:"인천광역시옹진군" },
    { id:"2900", content:"광주광역시" },
    { id:"2911", content:"광주광역시동구" },
    { id:"2914", content:"광주광역시서구" },
    { id:"2915", content:"광주광역시남구" },
    { id:"2917", content:"광주광역시북구" },
    { id:"2920", content:"광주광역시광산구" },
    { id:"3000", content:"대전광역시" },
    { id:"3011", content:"대전광역시동구" },
    { id:"3014", content:"대전광역시중구" },
    { id:"3017", content:"대전광역시서구" },
    { id:"3020", content:"대전광역시유성구" },
    { id:"3023", content:"대전광역시대덕구" },
    { id:"3100", content:"울산광역시" },
    { id:"3111", content:"울산광역시중구" },
    { id:"3114", content:"울산광역시남구" },
    { id:"3117", content:"울산광역시동구" },
    { id:"3120", content:"울산광역시북구" },
    { id:"3171", content:"울산광역시울주군" },
    { id:"3600", content:"세종특별자치시" },
    { id:"3611", content:"세종특별자치시" },
    { id:"4100", content:"경기도" },
    { id:"4111", content:"경기도수원시" },
    { id:"4113", content:"경기도성남시" },
    { id:"4115", content:"경기도의정부시" },
    { id:"4117", content:"경기도안양시" },
    { id:"4119", content:"경기도부천시" },
    { id:"4121", content:"경기도광명시" },
    { id:"4122", content:"경기도평택시" },
    { id:"4125", content:"경기도동두천시" },
    { id:"4127", content:"경기도안산시" },
    { id:"4128", content:"경기도고양시" },
    { id:"4129", content:"경기도과천시" },
    { id:"4131", content:"경기도구리시" },
    { id:"4136", content:"경기도남양주시" },
    { id:"4137", content:"경기도오산시" },
    { id:"4139", content:"경기도시흥시" },
    { id:"4141", content:"경기도군포시" },
    { id:"4143", content:"경기도의왕시" },
    { id:"4145", content:"경기도하남시" },
    { id:"4146", content:"경기도용인시" },
    { id:"4148", content:"경기도파주시" },
    { id:"4150", content:"경기도이천시" },
    { id:"4155", content:"경기도안성시" },
    { id:"4157", content:"경기도김포시" },
    { id:"4159", content:"경기도화성시" },
    { id:"4161", content:"경기도광주시" },
    { id:"4163", content:"경기도양주시" },
    { id:"4165", content:"경기도포천시" },
    { id:"4173", content:"경기도여주군" },
    { id:"4180", content:"경기도연천군" },
    { id:"4182", content:"경기도가평군" },
    { id:"4183", content:"경기도양평군" },
    { id:"4200", content:"강원도" },
    { id:"4211", content:"강원도춘천시" },
    { id:"4213", content:"강원도원주시" },
    { id:"4215", content:"강원도강릉시" },
    { id:"4217", content:"강원도동해시" },
    { id:"4219", content:"강원도태백시" },
    { id:"4221", content:"강원도속초시" },
    { id:"4223", content:"강원도삼척시" },
    { id:"4272", content:"강원도홍천군" },
    { id:"4273", content:"강원도횡성군" },
    { id:"4275", content:"강원도영월군" },
    { id:"4276", content:"강원도평창군" },
    { id:"4277", content:"강원도정선군" },
    { id:"4278", content:"강원도철원군" },
    { id:"4279", content:"강원도화천군" },
    { id:"4280", content:"강원도양구군" },
    { id:"4281", content:"강원도인제군" },
    { id:"4282", content:"강원도고성군" },
    { id:"4283", content:"강원도양양군" },
    { id:"4300", content:"충청북도" },
    { id:"4311", content:"충청북도청주시" },
    { id:"4313", content:"충청북도충주시" },
    { id:"4315", content:"충청북도제천시" },
    { id:"4371", content:"충청북도청원군" },
    { id:"4372", content:"충청북도보은군" },
    { id:"4373", content:"충청북도옥천군" },
    { id:"4374", content:"충청북도영동군" },
    { id:"4375", content:"충청북도진천군" },
    { id:"4376", content:"충청북도괴산군" },
    { id:"4377", content:"충청북도음성군" },
    { id:"4380", content:"충청북도단양군" },
    { id:"4400", content:"충청남도" },
    { id:"4413", content:"충청남도천안시" },
    { id:"4415", content:"충청남도공주시" },
    { id:"4418", content:"충청남도보령시" },
    { id:"4420", content:"충청남도아산시" },
    { id:"4421", content:"충청남도서산시" },
    { id:"4423", content:"충청남도논산시" },
    { id:"4425", content:"충청남도계룡시" },
    { id:"4427", content:"충청남도당진시" },
    { id:"4471", content:"충청남도금산군" },
    { id:"4476", content:"충청남도부여군" },
    { id:"4477", content:"충청남도서천군" },
    { id:"4479", content:"충청남도청양군" },
    { id:"4480", content:"충청남도홍성군" },
    { id:"4481", content:"충청남도예산군" },
    { id:"4482", content:"충청남도태안군" },
    { id:"4500", content:"전라북도" },
    { id:"4511", content:"전라북도전주시" },
    { id:"4513", content:"전라북도군산시" },
    { id:"4514", content:"전라북도익산시" },
    { id:"4518", content:"전라북도정읍시" },
    { id:"4519", content:"전라북도남원시" },
    { id:"4521", content:"전라북도김제시" },
    { id:"4571", content:"전라북도완주군" },
    { id:"4572", content:"전라북도진안군" },
    { id:"4573", content:"전라북도무주군" },
    { id:"4574", content:"전라북도장수군" },
    { id:"4575", content:"전라북도임실군" },
    { id:"4577", content:"전라북도순창군" },
    { id:"4579", content:"전라북도고창군" },
    { id:"4580", content:"전라북도부안군" },
    { id:"4600", content:"전라남도" },
    { id:"4611", content:"전라남도목포시" },
    { id:"4613", content:"전라남도여수시" },
    { id:"4615", content:"전라남도순천시" },
    { id:"4617", content:"전라남도나주시" },
    { id:"4623", content:"전라남도광양시" },
    { id:"4671", content:"전라남도담양군" },
    { id:"4672", content:"전라남도곡성군" },
    { id:"4673", content:"전라남도구례군" },
    { id:"4677", content:"전라남도고흥군" },
    { id:"4678", content:"전라남도보성군" },
    { id:"4679", content:"전라남도화순군" },
    { id:"4680", content:"전라남도장흥군" },
    { id:"4681", content:"전라남도강진군" },
    { id:"4682", content:"전라남도해남군" },
    { id:"4683", content:"전라남도영암군" },
    { id:"4684", content:"전라남도무안군" },
    { id:"4686", content:"전라남도함평군" },
    { id:"4687", content:"전라남도영광군" },
    { id:"4688", content:"전라남도장성군" },
    { id:"4689", content:"전라남도완도군" },
    { id:"4690", content:"전라남도진도군" },
    { id:"4691", content:"전라남도신안군" },
    { id:"4700", content:"경상북도" },
    { id:"4711", content:"경상북도포항시" },
    { id:"4713", content:"경상북도경주시" },
    { id:"4715", content:"경상북도김천시" },
    { id:"4717", content:"경상북도안동시" },
    { id:"4719", content:"경상북도구미시" },
    { id:"4721", content:"경상북도영주시" },
    { id:"4723", content:"경상북도영천시" },
    { id:"4725", content:"경상북도상주시" },
    { id:"4728", content:"경상북도문경시" },
    { id:"4729", content:"경상북도경산시" },
    { id:"4772", content:"경상북도군위군" },
    { id:"4773", content:"경상북도의성군" },
    { id:"4775", content:"경상북도청송군" },
    { id:"4776", content:"경상북도영양군" },
    { id:"4777", content:"경상북도영덕군" },
    { id:"4782", content:"경상북도청도군" },
    { id:"4783", content:"경상북도고령군" },
    { id:"4784", content:"경상북도성주군" },
    { id:"4785", content:"경상북도칠곡군" },
    { id:"4790", content:"경상북도예천군" },
    { id:"4792", content:"경상북도봉화군" },
    { id:"4793", content:"경상북도울진군" },
    { id:"4794", content:"경상북도울릉군" },
    { id:"4800", content:"경상남도" },
    { id:"4812", content:"경상남도창원시" },
    { id:"4817", content:"경상남도진주시" },
    { id:"4822", content:"경상남도통영시" },
    { id:"4824", content:"경상남도사천시" },
    { id:"4825", content:"경상남도김해시" },
    { id:"4827", content:"경상남도밀양시" },
    { id:"4831", content:"경상남도거제시" },
    { id:"4833", content:"경상남도양산시" },
    { id:"4872", content:"경상남도의령군" },
    { id:"4873", content:"경상남도함안군" },
    { id:"4874", content:"경상남도창녕군" },
    { id:"4882", content:"경상남도고성군" },
    { id:"4884", content:"경상남도남해군" },
    { id:"4885", content:"경상남도하동군" },
    { id:"4886", content:"경상남도산청군" },
    { id:"4887", content:"경상남도함양군" },
    { id:"4888", content:"경상남도거창군" },
    { id:"4889", content:"경상남도합천군" },
    { id:"5000", content:"제주특별자치도" },
    { id:"5011", content:"제주특별자치도제주시" },
    { id:"5013", content:"제주특별자치도서귀포시" },
];